#!/usr/bin/env bash
# script that pings an IP address 5 imes  passed as an argument

if [ $# -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

ip_address=$1
ping -c 5 "$ip_address"
