#!/usr/bin/env bash
# displaying hour and minutes

Hour=0
while [ "$Hour" -le 12 ]; do
echo "Hour: $Hour"

Minute=1
while [ "$Minute" -lt 60 ]; do
echo "$Minute"
Minute=$((Minute + 1))
done 

Hour=$((Hour + 1))
done
